debugging

diff --git a/.github/workflows/linux-ubuntu-deb-build-package.yml b/.github/workflows/linux-ubuntu-deb-build-package.yml
--- a/.github/workflows/linux-ubuntu-deb-build-package.yml
+++ b/.github/workflows/linux-ubuntu-deb-build-package.yml
@@ -11,29 +11,6 @@ env:
   GO111MODULE: "on"
 
 jobs:
-  pre-check-test:
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        go-version: ['1.17', '1.18', '1.19', '1.20']
-        go-arch: ['amd64', 'arm64']
-        go-opsys: ['linux', 'darwin']
-    steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v2
-
-      - name: Set up Go ${{ matrix.go-version }}
-        uses: actions/setup-go@v2
-        with:
-          go-version: ${{ matrix.go-version }}
-
-      - name: Install dependencies
-        run: go mod download -x
-
-      - name: Test with Go
-        run: |
-          go test -json ./...
-
   build:
     runs-on: ubuntu-latest
     strategy:
@@ -72,8 +49,12 @@ jobs:
           echo "Description: calculateSubnets binary" >> debian/DEBIAN/control
           mkdir -p debian/usr/bin
           ls -la
-          cp calculateSubnets debian/usr/bin
-          dpkg-deb --build debian
+          cp calculateSubnets debian/usr/bin || {
+            echo 'copy binary failed' && exit 1
+          }
+          dpkg-deb --build debian || {
+            echo 'dpkg-deb failed' && exit 1
+          }
           ls -la
           cp debian.deb subnetting-${{ matrix.go-opsys }}/${{ matrix.go-arch }}.$(date +%s)".deb
           ls -la
