fix typo I missed because I really need sleep tonight

diff --git a/.github/workflows/linux-ubuntu-deb-build-package.yml b/.github/workflows/linux-ubuntu-deb-build-package.yml
--- a/.github/workflows/linux-ubuntu-deb-build-package.yml
+++ b/.github/workflows/linux-ubuntu-deb-build-package.yml
@@ -47,15 +47,17 @@ jobs:
 
       - name: Create Debian/Ubuntu Package
         run: |
+          set -e
           cd build/
           mkdir -p debian/DEBIAN
-          echo "Package: calculateSubnets" > debian/DEBIAN/control
-          echo "Version: ${{ steps.set_version.outputs.version }}" >> debian/DEBIAN/control
-          echo "Architecture: ${{ matrix.go-arch }}" >> debian/DEBIAN/control
-          echo "Maintainer: Sam Caldwell <mail@samcaldwell.net>" >> debian/DEBIAN/control
-          echo "Description: calculateSubnets binary" >> debian/DEBIAN/control
           mkdir -p debian/usr/bin
-          ls -la
+          touch debian/DEBIAN/control || {echo 'touch failed' && exit 1}
+          echo "Package: calculateSubnets"                         >> debian/DEBIAN/control
+          echo "Version: ${{ steps.set_version.outputs.version }}" >> debian/DEBIAN/control
+          echo "Architecture: ${{ matrix.go-arch }}"               >> debian/DEBIAN/control
+          echo "Maintainer: Sam Caldwell <mail@samcaldwell.net>"   >> debian/DEBIAN/control
+          echo "Description: calculateSubnets binary"              >> debian/DEBIAN/control
+          ls -la debian/DEBIAN/
           cp calculateSubnets debian/usr/bin || {
             echo 'copy binary failed' && exit 1
           }
